language: c

env:
    matrix:
        - SMVERSION=1.7
        - SMVERSION=1.8
        - SMVERSION=1.9
        - SMVERSION=1.10
        - SMVERSION=1.11
    global:
        - CUSTOM_POSTFIX=_

matrix:
    fast_finish: true
    allow_failures:
    - env: SMVERSION=1.7
    - env: SMVERSION=1.11

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib lib32stdc++6

before_script:
    - mkdir sourcemod
    - cd sourcemod
    - wget -q "http://www.sourcemod.net/latest.php?version=$SMVERSION&os=linux" -O sourcemod.tar.gz
    - tar -xzf sourcemod.tar.gz
    - cp -Rf ../addons/sourcemod/scripting/* addons/sourcemod/scripting/
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh

script:
    - ./compile.sh sbpp_admcfg.sp sbpp_checker.sp sbpp_comms.sp sbpp_main.sp sbpp_sleuth.sp

before_deploy:
    - export CUSTOM_POSTFIX=$CUSTOM_POSTFIX$SMVERSION
    - mkdir -p $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY
    - cp -Rf $TRAVIS_BUILD_DIR/addons $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons
    - rm -Rf $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/plugins/*
    - mkdir -p $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/plugins/optional
    - cp compiled/* $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/plugins/
    - cd $TRAVIS_BUILD_DIR
    - tar -cvf ../sbma-oldplugin.${SMVERSION}.tar.gz .

deploy:
    - provider: script
      skip_cleanup: true
      script: curl "${API_URL}?secret_key=${API_KEY}&tags=SourceMod%20${SMVERSION}" -F "artifact=@./../sbma-oldplugin.${SMVERSION}.tar.gz"
